<?php

	include "global.php";
	
	$contents = [
		"ESTJ" => ["images/10.png", "Executives are representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together. Embracing the values of honesty, dedication and dignity, people with the Executive personality type are valued for their clear advice and guidance, and they happily lead the way on difficult paths. Taking pride in bringing people together, Executives often take on roles as community organizers, working hard to bring everyone together in celebration of cherished local events, or in defense of the traditional values that hold families and communities together.", "“Good order is the foundation of all things.” (EDMUND BURKE)"],
		"ISTJ" => ["images/8.png", "Logisticians pride themselves on their integrity. People with this personality type mean what they say, and when they commit to doing something, they make sure to follow through. This personality type makes up a good portion of the overall population, and while Logisticians may not be particularly flashy or attention-seeking, they do more than their share to keep society on a sturdy, stable foundation. In their families and their communities, Logisticians often earn respect for their reliability, their practicality, and their ability to stay grounded and logical, even in the most stressful situations.", "“I’d be more frightened by not using whatever abilities I’d been given. I’d be more frightened by procrastination and laziness.” (DENZEL WASHINGTON)"],
		"ISFJ" => ["images/9.png", "In their unassuming, understated way, Defenders help make the world go round. Hardworking and devoted, people with this personality type feel a deep sense of responsibility to those around them. Defenders can be counted on to meet deadlines, remember birthdays and special occasions, uphold traditions, and shower their loved ones with gestures of care and support. But they rarely demand recognition for all that they do, preferring instead to operate behind the scenes. This is a capable, can-do personality type, with a wealth of versatile gifts. Though sensitive and caring, Defenders also have excellent analytical abilities and an eye for detail. And despite their reserve, they tend to have well-developed people skills and robust social relationships. Defenders are truly more than the sum of their parts, and their varied strengths shine in even the most ordinary aspects of their daily lives.", "“Love only grows by sharing. You can only have more for yourself by giving it away to others.” (BRIAN TRACY)"],
		"ESFJ" => ["images/11.png", "For Consuls, life is sweetest when it’s shared with others. People with this personality type form the bedrock of many communities, opening their homes – and their hearts – to friends, loved ones, and neighbors. This doesn’t mean that Consuls like everyone, or that they’re saints. But Consuls do believe in the power of hospitality and good manners, and they tend to feel a sense of duty to those around them. Generous and reliable, people with this personality type often take it upon themselves – in ways both large and small – to hold their families and their communities together.", "“Encourage, lift, and strengthen one another. For the positive energy spread to one will be felt by us all.” (DEBORAH DAY)"],
		"ESFP" => ["images/12.png", "If anyone is to be found spontaneously breaking into song and dance, it is the Entertainer personality type. Entertainers get caught up in the excitement of the moment, and want everyone else to feel that way, too. No other personality type is as generous with their time and energy as Entertainers when it comes to encouraging others, and no other personality type does it with such irresistible style.", "“Live for each second without hesitation.” (ELTON JOHN)"],
		"ESTP" => ["images/13.png", "Entrepreneurs always have an impact on their immediate surroundings – the best way to spot them at a party is to look for the whirling eddy of people flitting about them as they move from group to group. Laughing and entertaining with a blunt and earthy humor, Entrepreneur personalities love to be the center of attention. If an audience member is asked to come on stage, Entrepreneurs volunteer – or volunteer a shy friend. Theory, abstract concepts and plodding discussions about global issues and their implications don’t keep Entrepreneurs interested for long. Entrepreneurs keep their conversation energetic, with a good dose of intelligence, but they like to talk about what is – or better yet, to just go out and do it. Entrepreneurs leap before they look, fixing their mistakes as they go, rather than sitting idle, preparing contingencies and escape clauses.", "“Life is either a daring adventure or nothing at all.” (HELEN KELLER)"],
		"ISFP" => ["images/14.png", "Adventurers are true artists – although not necessarily in the conventional sense. For this personality type, life itself is a canvas for self-expression. From what they wear to how they spend their free time, Adventurers act in ways that vividly reflect who they are as unique individuals. And every Adventurer is certainly unique. Driven by curiosity and eager to try new things, people with this personality often have a fascinating array of passions and interests. With their exploratory spirits and their ability to find joy in everyday life, Adventurers can be among the most interesting people you’ll ever meet. The only irony? Unassuming and humble, Adventurers tend to see themselves as “just doing their own thing,” so they may not even realize how remarkable they really are.", "“I change during the course of a day. I wake and I’m one person, and when I go to sleep I know for certain I’m somebody else.” (BOB DYLAN)"],
		"ISTP" => ["images/15.png", "Virtuosos love to explore with their hands and their eyes, touching and examining the world around them with cool rationalism and spirited curiosity. People with this personality type are natural Makers, moving from project to project, building the useful and the superfluous for the fun of it, and learning from their environment as they go. Often mechanics and engineers, Virtuosos find no greater joy than in getting their hands dirty pulling things apart and putting them back together, just a little bit better than they were before.", "“I wanted to live the life, a different life. I didn’t want to go to the same place every day and see the same people and do the same job. I wanted interesting challenges.” (HARRISON FORD)"],
		"ENFJ" => ["images/0.png", "Protagonists (ENFJs) feel called to serve a greater purpose in life. Thoughtful and idealistic, these personality types strive to have a positive impact on other people and the world around them. They rarely shy away from an opportunity to do the right thing, even when doing so is far from easy. Protagonists are born leaders, which explains why these personalities can be found among many notable politicians, coaches, and teachers. Their passion and charisma allow them to inspire others not just in their careers but in every arena of their lives, including their relationships. Few things bring Protagonists a deeper sense of joy and fulfillment than guiding friends and loved ones to grow into their best selves.", "“When the whole world is silent, even one voice becomes powerful.” (MALALA YOUSAFZAI)"],
		"INFJ" => ["images/1.png", "Advocates (INFJs) may be the rarest personality type of all, but they certainly leave their mark on the world. Idealistic and principled, they aren’t content to coast through life – they want to stand up and make a difference. For Advocate personalities, success doesn’t come from money or status but from seeking fulfillment, helping others, and being a force for good in the world. While they have lofty goals and ambitions, Advocates shouldn’t be mistaken for idle dreamers. People with this personality type care about integrity, and they’re rarely satisfied until they’ve done what they know to be right. Conscientious to the core, they move through life with a clear sense of their values, and they aim never to lose sight of what truly matters – not according to other people or society at large, but according to their own wisdom and intuition.", "“Treat people as if they were what they ought to be and you help them to become what they are capable of being.” (JOHANN WOLFGANG VON GOETHE)"],
		"INFP" => ["images/2.png", "Although they may seem quiet or unassuming, Mediators (INFPs) have vibrant, passionate inner lives. Creative and imaginative, they happily lose themselves in daydreams, inventing all sorts of stories and conversations in their minds. These personalities are known for their sensitivity – Mediators can have profound emotional responses to music, art, nature, and the people around them. Idealistic and empathetic, Mediators long for deep, soulful relationships, and they feel called to help others. But because this personality type makes up such a small portion of the population, Mediators may sometimes feel lonely or invisible, adrift in a world that doesn’t seem to appreciate the traits that make them unique.", "“All that is gold does not glitter; not all those who wander are lost; the old that is strong does not wither; deep roots are not reached by the frost.” (J. R. R. TOLKIEN)"],
		"ENFP" => ["images/3.png", "Campaigners (ENFPs) are true free spirits – outgoing, openhearted, and open-minded. With their lively, upbeat approach to life, they stand out in any crowd. But even though they can be the life of the party, Campaigners don’t just care about having a good time. These personality types run deep – as does their longing for meaningful, emotional connections with other people.", "“It doesn’t interest me what you do for a living. I want to know what you ache for – and if you dare to dream of meeting your heart’s longing.” (ORIAH MOUNTAIN DREAMER)"],
		"ENTP" => ["images/4.png", "Quick-witted and audacious, Debaters aren’t afraid to disagree with the status quo. In fact, they’re not afraid to disagree with pretty much anything or anyone. Few things light up people with this personality type more than a bit of verbal sparring – and if the conversation veers into controversial terrain, so much the better. It would be a mistake, though, to think of Debaters as disagreeable or mean-spirited. Instead, people with this personality type are knowledgeable and curious, with a playful sense of humor, and they can be incredibly entertaining. They simply have an offbeat, contrarian idea of fun – one that involves a healthy dose of spirited debate.", "“Follow the path of the unsafe, independent thinker. Expose your ideas to the dangers of controversy.” (TOMAS J. WATSON)"],
		"ENTJ" => ["images/5.png", "Commanders are natural-born leaders. People with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal. However, Commanders are also characterized by an often ruthless level of rationality, using their drive, determination and sharp minds to achieve whatever end they’ve set for themselves. Perhaps it is best that they make up only three percent of the population, lest they overwhelm the more timid and sensitive personality types that make up much of the rest of the world – but we have Commanders to thank for many of the businesses and institutions we take for granted every day.", "“Your time is limited, so don’t waste it living someone else’s life.” (STEVE JOBS)"],
		"INTP" => ["images/6.png", "Logicians pride themselves on their unique perspectives and vigorous intellect. They can’t help but puzzle over the mysteries of the universe – which may explain why some of the most influential philosophers and scientists of all time have been Logicians. This personality type is fairly rare, but with their creativity and inventiveness, Logicians aren’t afraid to stand out from the crowd.", "“The important thing is not to stop questioning. Curiosity has its own reason for existence.” (ALBERT EINSTEIN)"],
		"INTJ" => ["images/7.png", "It can be lonely at the top. As one of the rarest personality types – and one of the most capable – Architects (INTJs) know this all too well. Rational and quick-witted, Architects pride themselves on their ability to think for themselves, not to mention their uncanny knack for seeing right through phoniness and hypocrisy. But because their minds are never at rest, Architects may struggle to find people who can keep up with their nonstop analysis of everything around them.", "“Thought constitutes the greatness of man. Man is a reed, the feeblest thing in nature, but he is a thinking reed.” (BLAISE PASCAL)"],
	];
	
	
	$index = "ESTJ";
	if (!empty($_GET)) {
		$index = $_GET["ei-select"].$_GET["sn-select"].$_GET["tf-select"].$_GET["jp-select"];
	}
	
	$content = get("templates/authed_content.html");
	if ($index[0] == "E") {
		$content = replace($content, "{{ e }}", 'selected="selected"');
		$content = replace($content, "{{ i }}", "");
	} else {
		$content = replace($content, "{{ i }}", 'selected="selected"');
		$content = replace($content, "{{ e }}", "");
	}	
	if ($index[1] == "S") {
		$content = replace($content, "{{ s }}", 'selected="selected"');
		$content = replace($content, "{{ n }}", "");
	} else {
		$content = replace($content, "{{ n }}", 'selected="selected"');
		$content = replace($content, "{{ s }}", "");
	}	
	if ($index[2] == "T") {
		$content = replace($content, "{{ t }}", 'selected="selected"');
		$content = replace($content, "{{ f }}", "");
	} else {
		$content = replace($content, "{{ f }}", 'selected="selected"');
		$content = replace($content, "{{ t }}", "");
	}	
	if ($index[3] == "J") {
		$content = replace($content, "{{ j }}", 'selected="selected"');
		$content = replace($content, "{{ p }}", "");
	} else {
		$content = replace($content, "{{ p }}", 'selected="selected"');
		$content = replace($content, "{{ j }}", "");
	}	
	$content = replace($content, "{{ person_logo }}", $contents[$index][0]);
	$content = replace($content, "{{ person_text }}", $contents[$index][1]);
	$content = replace($content, "{{ person_quote }}", $contents[$index][2]);
	
	
	$main = base("css/auth_info.css", "Personalities", $content);
	
	echo $main;

